### ISSUE TITLE
WRONG CODE

### ISSUE THREAD

**Issue by nikhilteja91** [nzahasan/pyscissor#1]

**Comment by nzahasan** [comment]
Thanks for coming to the quick conclusion! Have you considered how you checked is wrong! Can you share some detail on this? perhaps paste the full code!

**Comment by nikhilteja91** [comment]
> Thanks for coming to the quick conclusion! Have you considered how you checked is wrong! Can you share some detail on this? perhaps paste the full code!

Sorry for that! Will try it next time and then let you know. Sorry.
